import {
  PROFILE_PICTURE_MAX_BYTES,
  PROFILE_PICTURE_SIZE as SHARED_PROFILE_PICTURE_SIZE,
} from '@antin-os/shared';

export const PROFILE_SINGLETON_KEY = 'owner';
export const MAX_PROFILE_PICTURE_BYTES = PROFILE_PICTURE_MAX_BYTES;
export const PROFILE_PICTURE_SIZE = SHARED_PROFILE_PICTURE_SIZE;
